#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Original blue
# active_window_border_color 0xff0398fc   \
# Original purple
# normal_window_border_color 0xff6f03fc   \
yabai -m config \
    external_bar               all:25:0       \
    mouse_follows_focus        on             \
    focus_follows_mouse        autoraise      \
    window_origin_display      cursor         \
    window_placement           second_child   \
    window_zoom_persist        off            \
    window_topmost             off            \
    window_shadow              off            \
    window_animation_duration  0.0            \
    window_animation_frame_rate 120           \
    window_opacity_duration    0.25           \
    active_window_opacity      1            \
    normal_window_opacity      1            \
    window_opacity             on             \
    insert_feedback_color      0xff9dd274     \
    active_window_border_color 0xff7aa2f7     \
    normal_window_border_color 0xff1a1b26     \
    window_border_width        2              \
    window_border_radius       12             \
    window_border_blur         on             \
    window_border_hidpi        off            \
    window_border              on             \
    split_ratio                0.50           \
    split_type                 auto           \
    auto_balance               off            \
    top_padding                8              \
    bottom_padding             8              \
    left_padding               8              \
    right_padding              8              \
    window_gap                 8              \
    layout                     bsp            \
    mouse_modifier             fn             \
    mouse_action1              move           \
    mouse_action2              resize         \
    mouse_drop_action          swap           \

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config layout bsp

# yabai -m signal --add event=window_focused action='zsh ~/.config/yabai/window.zsh'
# yabai -m signal --add event=window_destroyed action='zsh ~/.config/yabai/window.zsh'
# yabai -m signal --add event=space_focused action='zsh ~/.config/yabai/window.zsh'

# Move focus to window under cursor when a window is closed 
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
echo "yabai configuration loaded.."
