#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config external_bar               all:40:0     \
                window_border              on           \
                mouse_follows_focus        on          \
                focus_follows_mouse        on          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.25          \
                active_window_opacity      0.95          \
                normal_window_opacity      0.85          \
                window_border_width        1            \
                window_border_hidpi        off          \
                window_border_radius       12           \
                window_border_blur         on          \
                window_animation_duration  0          \
                active_window_border_color 0xff0398fc   \
                normal_window_border_color 0xff6f03fc   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off           \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             10            \
                left_padding               10            \
                right_padding              10            \
                window_gap                 8 

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config layout bsp

# yabai -m signal --add event=window_focused action='zsh ~/.config/yabai/window.zsh'
# yabai -m signal --add event=window_destroyed action='zsh ~/.config/yabai/window.zsh'
# yabai -m signal --add event=space_focused action='zsh ~/.config/yabai/window.zsh'

echo "yabai configuration loaded.."
