local opt = vim.opt

-- opt.colorcolumn = '80'
opt.autochdir = false
opt.conceallevel = 0
opt.cmdheight = 0
opt.cursorcolumn = false
opt.cursorline = true
opt.cursorlineopt = "both"
opt.expandtab = true
opt.ignorecase = true
opt.incsearch = true
opt.laststatus = 3
opt.mouse = "a"
opt.number = true
opt.numberwidth = 2
opt.relativenumber = true
opt.scrolloff = 8
opt.shiftwidth = 4
opt.showmode = false
opt.showmode = false
opt.showtabline = 1
opt.sidescroll = 1
opt.sidescrolloff = 8
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 4
opt.termguicolors = true
opt.timeout = true
opt.timeoutlen = 250
opt.title = true
opt.updatetime = 50
opt.wrap = false

vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.netrw_banner = 0
vim.g.netrw_winsize = 40
vim.g.netrw_liststyle = 3
