[colors]
   # compose_cursor = "#ecd3a0"
    foreground = "#b6beca"
    background = "#0d0f18"
    cursor_bg = "#ecd3a0" # "#cbced3"
    cursor_border = "#d0d3d8"
    cursor_fg = "#151720"
    selection_bg = "#575268"
    selection_fg = "#D9E0EE"
    ansi = [ "#1c252c", "#dd6777", "#90ceaa", "#ecd3a0", "#86aaec", "#c296eb", "#93cee9", "#cbced3" ]
    brights = [ "#1c1e27", "#e26c7c", "#95d3af", "#f1d8a5", "#8baff1", "#c79bf0", "#89d3ee", "#d0d3d8" ]
